language: "perl"
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"

before_install:
    # optional dependencies
    - cpanm Test::CPAN::Changes Test::Pod::Coverage Test::TrailingSpace

install:
    - cd File-Dir-Dumper
    - cpanm -v --installdeps --notest .

script:
    - perl Build.PL
    - ./Build test
